import { StayType } from "@prisma/client";

/**
 * 50 stays in Europe and the Americas only — real street context + lat/lng for maps.
 * location = guest-facing area; full address in street/city/state/postal.
 */
export const LISTING_SPECS = [
  {
    title: "Algarve cliff-view apartment",
    description:
      "Bright flat near Praia Dona Ana; short walk to Lagos marina.",
    stayType: StayType.RENTAL_ROOM,
    location: "Lagos, Portugal",
    country: "Portugal",
    streetLine1: "Rua Infante de Sagres 68",
    city: "Lagos",
    stateRegion: "Algarve",
    postalCode: "8600-315",
    lat: 37.1028,
    lng: -8.6733,
    pricePerNight: 124,
    weekday: 124,
    weekend: 159,
    maxGuests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1.5,
    guestFavorites: [
      "Wifi",
      "Kitchen",
      "Washer",
      "Dedicated workspace",
      "Air conditioning",
    ],
    standoutAmenities: ["Pool", "Hot tub", "Patio", "Beach access"],
    safetyAmenities: [
      "Smoke alarm",
      "Carbon monoxide alarm",
      "First aid kit",
    ],
    hostLanguages: ["English", "Portuguese"],
  },
  {
    title: "Cozy B&B room downtown",
    description: "Private room with breakfast in a quiet neighborhood.",
    stayType: StayType.BNB_ROOM,
    location: "Lisbon, Portugal",
    country: "Portugal",
    streetLine1: "Rua do Alecrim 21",
    city: "Lisbon",
    stateRegion: "Lisbon",
    postalCode: "1200-017",
    lat: 38.7127,
    lng: -9.1456,
    pricePerNight: 98,
    weekday: 98,
    weekend: 128,
    maxGuests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    guestFavorites: ["Wifi", "TV", "Kitchen", "Dedicated workspace"],
    standoutAmenities: ["Indoor fireplace", "Patio"],
    safetyAmenities: ["Smoke alarm", "Fire extinguisher"],
    hostLanguages: ["English", "Portuguese", "Spanish"],
  },
  {
    title: "Garden cabin with hot tub",
    description: "Quiet cabin with a private hot tub and big garden.",
    stayType: StayType.HOTEL_ROOM,
    location: "Reykjavík, Iceland",
    country: "Iceland",
    streetLine1: "Laugavegur 28",
    city: "Reykjavík",
    stateRegion: "Capital Region",
    postalCode: "101",
    lat: 64.1451,
    lng: -21.9293,
    pricePerNight: 140,
    weekday: 140,
    weekend: 190,
    maxGuests: 3,
    bedrooms: 1,
    beds: 2,
    bathrooms: 1,
    guestFavorites: ["Wifi", "Kitchen", "Heating"],
    standoutAmenities: ["Hot tub", "Fire pit", "Patio"],
    safetyAmenities: ["Smoke alarm", "First aid kit"],
    hostLanguages: ["English"],
  },
  {
    title: "Sunset apartment with city view",
    description: "Modern apartment with panoramic sunset views.",
    stayType: StayType.RENTAL_ROOM,
    location: "Barcelona, Spain",
    country: "Spain",
    streetLine1: "Passeig de Gràcia 43",
    city: "Barcelona",
    stateRegion: "Catalonia",
    postalCode: "08007",
    lat: 41.3911,
    lng: 2.165,
    pricePerNight: 110,
    weekday: 110,
    weekend: 145,
    maxGuests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1.2,
    guestFavorites: ["Wifi", "Air conditioning", "Dedicated workspace"],
    standoutAmenities: ["Balcony", "Fast Wi-Fi"],
    safetyAmenities: ["Smoke alarm"],
    hostLanguages: ["English", "Spanish"],
  },
  {
    title: "Soho loft near Washington Square",
    description: "Walk-up loft with exposed brick and fast subway access.",
    stayType: StayType.RENTAL_ROOM,
    location: "New York, NY",
    country: "United States",
    streetLine1: "175 Thompson St",
    city: "New York",
    stateRegion: "NY",
    postalCode: "10012",
    lat: 40.7282,
    lng: -73.9995,
    pricePerNight: 189,
    weekday: 179,
    weekend: 219,
    maxGuests: 3,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
  },
  {
    title: "Foggy Victorian flat",
    description: "Two-bedroom flat two blocks from Alamo Square park.",
    stayType: StayType.RENTAL_ROOM,
    location: "San Francisco, CA",
    country: "United States",
    streetLine1: "712 Steiner St",
    city: "San Francisco",
    stateRegion: "CA",
    postalCode: "94117",
    lat: 37.7763,
    lng: -122.4348,
    pricePerNight: 165,
    weekday: 155,
    weekend: 195,
    maxGuests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
  },
  {
    title: "Magnificent Mile high-rise studio",
    description: "Floor-to-ceiling windows overlooking the river.",
    stayType: StayType.HOTEL_ROOM,
    location: "Chicago, IL",
    country: "United States",
    streetLine1: "233 E Wacker Dr",
    city: "Chicago",
    stateRegion: "IL",
    postalCode: "60601",
    lat: 41.8874,
    lng: -87.6173,
    pricePerNight: 142,
    weekday: 132,
    weekend: 172,
    maxGuests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
  },
  {
    title: "Capitol Hill townhome",
    description: "Renovated row house near Eastern Market Metro.",
    stayType: StayType.BNB_ROOM,
    location: "Washington, DC",
    country: "United States",
    streetLine1: "225 7th St SE",
    city: "Washington",
    stateRegion: "DC",
    postalCode: "20003",
    lat: 38.884,
    lng: -76.9965,
    pricePerNight: 138,
    weekday: 128,
    weekend: 168,
    maxGuests: 3,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1.5,
  },
  {
    title: "South Congress bungalow",
    description: "Private bungalow with a pecan-shaded patio.",
    stayType: StayType.RENTAL_ROOM,
    location: "Austin, TX",
    country: "United States",
    streetLine1: "1604 S Congress Ave",
    city: "Austin",
    stateRegion: "TX",
    postalCode: "78704",
    lat: 30.2458,
    lng: -97.7505,
    pricePerNight: 112,
    weekday: 105,
    weekend: 135,
    maxGuests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
  },
  {
    title: "Pearl District penthouse",
    description: "Top-floor condo steps from independent shops and cafés.",
    stayType: StayType.RENTAL_ROOM,
    location: "Portland, OR",
    country: "United States",
    streetLine1: "1022 NW Marshall St",
    city: "Portland",
    stateRegion: "OR",
    postalCode: "97209",
    lat: 45.5309,
    lng: -122.682,
    pricePerNight: 128,
    weekday: 118,
    weekend: 158,
    maxGuests: 3,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2,
  },
  {
    title: "Waikiki walk-up studio",
    description: "Five-minute walk to Kuhio Beach; AC and in-unit laundry.",
    stayType: StayType.HOTEL_ROOM,
    location: "Honolulu, HI",
    country: "United States",
    streetLine1: "2427 Kuhio Ave",
    city: "Honolulu",
    stateRegion: "HI",
    postalCode: "96815",
    lat: 21.2784,
    lng: -157.8287,
    pricePerNight: 155,
    weekday: 145,
    weekend: 185,
    maxGuests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
  },
  {
    title: "Brickell waterfront condo",
    description: "Pool deck views of Biscayne Bay; valet available.",
    stayType: StayType.RENTAL_ROOM,
    location: "Miami, FL",
    country: "United States",
    streetLine1: "1200 Brickell Bay Dr",
    city: "Miami",
    stateRegion: "FL",
    postalCode: "33131",
    lat: 25.7617,
    lng: -80.1918,
    pricePerNight: 178,
    weekday: 168,
    weekend: 208,
    maxGuests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2,
  },
  {
    title: "Midtown tree-lined flat",
    description: "Near Piedmont Park; ideal for longer stays.",
    stayType: StayType.BNB_ROOM,
    location: "Atlanta, GA",
    country: "United States",
    streetLine1: "587 Peachtree St NE",
    city: "Atlanta",
    stateRegion: "GA",
    postalCode: "30308",
    lat: 33.771,
    lng: -84.3856,
    pricePerNight: 104,
    weekday: 98,
    weekend: 124,
    maxGuests: 3,
    bedrooms: 1,
    beds: 2,
    bathrooms: 1,
  },
  {
    title: "Deep Ellum artist loft",
    description: "Converted warehouse with mural courtyard access.",
    stayType: StayType.RENTAL_ROOM,
    location: "Dallas, TX",
    country: "United States",
    streetLine1: "2650 Commerce St",
    city: "Dallas",
    stateRegion: "TX",
    postalCode: "75226",
    lat: 32.7831,
    lng: -96.7795,
    pricePerNight: 98,
    weekday: 92,
    weekend: 118,
    maxGuests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1.5,
  },
  {
    title: "Montrose carriage house",
    description: "Quiet guest house near museums and brunch spots.",
    stayType: StayType.BNB_ROOM,
    location: "Houston, TX",
    country: "United States",
    streetLine1: "1415 Vermont St",
    city: "Houston",
    stateRegion: "TX",
    postalCode: "77006",
    lat: 29.741,
    lng: -95.3904,
    pricePerNight: 91,
    weekday: 85,
    weekend: 110,
    maxGuests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
  },
  {
    title: "Old Town Scottsdale casita",
    description: "Adobe-style guest suite with private entrance.",
    stayType: StayType.RENTAL_ROOM,
    location: "Scottsdale, AZ",
    country: "United States",
    streetLine1: "4000 N Drinkwater Blvd",
    city: "Scottsdale",
    stateRegion: "AZ",
    postalCode: "85251",
    lat: 33.5021,
    lng: -111.9251,
    pricePerNight: 118,
    weekday: 110,
    weekend: 142,
    maxGuests: 3,
    bedrooms: 1,
    beds: 2,
    bathrooms: 1,
  },
  {
    title: "Rittenhouse brownstone room",
    description: "Front parlor room in historic 1880s home.",
    stayType: StayType.BNB_ROOM,
    location: "Philadelphia, PA",
    country: "United States",
    streetLine1: "1907 Spruce St",
    city: "Philadelphia",
    stateRegion: "PA",
    postalCode: "19103",
    lat: 39.9489,
    lng: -75.1732,
    pricePerNight: 102,
    weekday: 96,
    weekend: 122,
    maxGuests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
  },
  {
    title: "Kitsilano garden suite",
    description: "Ground-floor suite near Kits Beach.",
    stayType: StayType.RENTAL_ROOM,
    location: "Vancouver, BC",
    country: "Canada",
    streetLine1: "2201 Cornwall Ave",
    city: "Vancouver",
    stateRegion: "BC",
    postalCode: "V6K 1B4",
    lat: 49.2727,
    lng: -123.1528,
    pricePerNight: 134,
    weekday: 124,
    weekend: 162,
    maxGuests: 3,
    bedrooms: 1,
    beds: 2,
    bathrooms: 1,
  },
  {
    title: "King West condo",
    description: "Glass tower suite with CN Tower glimpses.",
    stayType: StayType.HOTEL_ROOM,
    location: "Toronto, ON",
    country: "Canada",
    streetLine1: "550 Wellington St W",
    city: "Toronto",
    stateRegion: "ON",
    postalCode: "M5V 2V4",
    lat: 43.6452,
    lng: -79.4023,
    pricePerNight: 148,
    weekday: 138,
    weekend: 176,
    maxGuests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
  },
  {
    title: "Plateau Mile End walk-up",
    description: "Bright 2BR near bagel shops and Parc du Mont-Royal.",
    stayType: StayType.RENTAL_ROOM,
    location: "Montreal, QC",
    country: "Canada",
    streetLine1: "74 Rue Fairmount O",
    city: "Montreal",
    stateRegion: "QC",
    postalCode: "H2T 2M2",
    lat: 45.5231,
    lng: -73.593,
    pricePerNight: 98,
    weekday: 92,
    weekend: 118,
    maxGuests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
  },
  {
    title: "Roma Norte apartment",
    description: "Tree-lined Calle Orizaba; galleries within blocks.",
    stayType: StayType.RENTAL_ROOM,
    location: "Mexico City, Mexico",
    country: "Mexico",
    streetLine1: "Calle Orizaba 42",
    city: "Mexico City",
    stateRegion: "CDMX",
    postalCode: "06700",
    lat: 19.4195,
    lng: -99.161,
    pricePerNight: 72,
    weekday: 68,
    weekend: 88,
    maxGuests: 3,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
  },
  {
    title: "Notting Hill mews house",
    description: "Quiet cobbled mews near Portobello Market.",
    stayType: StayType.RENTAL_ROOM,
    location: "London, UK",
    country: "United Kingdom",
    streetLine1: "29 Chepstow Villas",
    city: "London",
    stateRegion: "England",
    postalCode: "W11 3BA",
    lat: 51.5088,
    lng: -0.1963,
    pricePerNight: 195,
    weekday: 185,
    weekend: 225,
    maxGuests: 4,
    bedrooms: 2,
    beds: 3,
    bathrooms: 1.5,
  },
  {
    title: "Le Marais atelier loft",
    description: "Skylit workspace + sofa bed for extra guests.",
    stayType: StayType.BNB_ROOM,
    location: "Paris, France",
    country: "France",
    streetLine1: "14 Rue des Rosiers",
    city: "Paris",
    stateRegion: "Île-de-France",
    postalCode: "75004",
    lat: 48.8575,
    lng: 2.3615,
    pricePerNight: 168,
    weekday: 158,
    weekend: 198,
    maxGuests: 3,
    bedrooms: 1,
    beds: 2,
    bathrooms: 1,
  },
  {
    title: "Kreuzberg canal-side flat",
    description: "Bike-friendly block near Paul-Lincke-Ufer.",
    stayType: StayType.RENTAL_ROOM,
    location: "Berlin, Germany",
    country: "Germany",
    streetLine1: "Paul-Lincke-Ufer 42",
    city: "Berlin",
    stateRegion: "Berlin",
    postalCode: "10999",
    lat: 52.4975,
    lng: 13.4262,
    pricePerNight: 88,
    weekday: 82,
    weekend: 104,
    maxGuests: 3,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
  },
  {
    title: "Trastevere townhouse room",
    description: "Host lives upstairs; private bath and mini fridge.",
    stayType: StayType.BNB_ROOM,
    location: "Rome, Italy",
    country: "Italy",
    streetLine1: "Vicolo del Bologna 12",
    city: "Rome",
    stateRegion: "Lazio",
    postalCode: "00153",
    lat: 41.8834,
    lng: 12.4695,
    pricePerNight: 96,
    weekday: 90,
    weekend: 118,
    maxGuests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
  },
  {
    title: "Jordaan canal studio",
    description: "Narrow house studio with bicycle included.",
    stayType: StayType.HOTEL_ROOM,
    location: "Amsterdam, Netherlands",
    country: "Netherlands",
    streetLine1: "Brouwersgracht 30",
    city: "Amsterdam",
    stateRegion: "North Holland",
    postalCode: "1013 HA",
    lat: 52.3846,
    lng: 4.8872,
    pricePerNight: 142,
    weekday: 132,
    weekend: 172,
    maxGuests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
  },
  {
    title: "Temple Bar Georgian flat",
    description: "Live music and pubs two minutes away.",
    stayType: StayType.RENTAL_ROOM,
    location: "Dublin, Ireland",
    country: "Ireland",
    streetLine1: "18 Eustace St",
    city: "Dublin",
    stateRegion: "Leinster",
    postalCode: "D02 X251",
    lat: 53.3444,
    lng: -6.2668,
    pricePerNight: 124,
    weekday: 116,
    weekend: 148,
    maxGuests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
  },
  {
    title: "Old Town Royal Mile flat",
    description: "Stone stairs; unbeatable festival location.",
    stayType: StayType.RENTAL_ROOM,
    location: "Edinburgh, UK",
    country: "United Kingdom",
    streetLine1: "333 High St",
    city: "Edinburgh",
    stateRegion: "Scotland",
    postalCode: "EH1 1PN",
    lat: 55.9496,
    lng: -3.1906,
    pricePerNight: 118,
    weekday: 110,
    weekend: 142,
    maxGuests: 3,
    bedrooms: 1,
    beds: 2,
    bathrooms: 1,
  },
  {
    title: "Altstadt riverside room",
    description: "Hotel-quality linens in a family-run B&B.",
    stayType: StayType.BNB_ROOM,
    location: "Zurich, Switzerland",
    country: "Switzerland",
    streetLine1: "Limmatquai 88",
    city: "Zurich",
    stateRegion: "Zurich",
    postalCode: "8001",
    lat: 47.3719,
    lng: 8.5417,
    pricePerNight: 185,
    weekday: 175,
    weekend: 215,
    maxGuests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
  },
  {
    title: "Innere Stadt apartment",
    description: "Across from Stadtpark; tram at the corner.",
    stayType: StayType.RENTAL_ROOM,
    location: "Vienna, Austria",
    country: "Austria",
    streetLine1: "Am Heumarkt 15",
    city: "Vienna",
    stateRegion: "Vienna",
    postalCode: "1030",
    lat: 48.1975,
    lng: 16.3842,
    pricePerNight: 108,
    weekday: 100,
    weekend: 128,
    maxGuests: 3,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
  },
  {
    title: "Malá Strana attic suite",
    description: "Castle views from dormer windows.",
    stayType: StayType.HOTEL_ROOM,
    location: "Prague, Czechia",
    country: "Czechia",
    streetLine1: "Mostecká 21",
    city: "Prague",
    stateRegion: "Prague",
    postalCode: "118 00",
    lat: 50.0878,
    lng: 14.4056,
    pricePerNight: 94,
    weekday: 88,
    weekend: 114,
    maxGuests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
  },
  {
    title: "La Latina tapas district stay",
    description: "Interior patio; great for food-focused trips.",
    stayType: StayType.RENTAL_ROOM,
    location: "Madrid, Spain",
    country: "Spain",
    streetLine1: "Calle Cava Baja 23",
    city: "Madrid",
    stateRegion: "Madrid",
    postalCode: "28005",
    lat: 40.4117,
    lng: -3.7087,
    pricePerNight: 92,
    weekday: 86,
    weekend: 112,
    maxGuests: 3,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
  },
  {
    title: "Plaka walk-up under Acropolis",
    description: "Narrow stairs; rooftop terrace shared with one neighbor.",
    stayType: StayType.BNB_ROOM,
    location: "Athens, Greece",
    country: "Greece",
    streetLine1: "24 Tripodon St",
    city: "Athens",
    stateRegion: "Attica",
    postalCode: "105 58",
    lat: 37.9715,
    lng: 23.7267,
    pricePerNight: 78,
    weekday: 74,
    weekend: 94,
    maxGuests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
  },
  {
    title: "Nyhavn harbor hotel room",
    description: "Compact nautical room; harbor breakfast nearby.",
    stayType: StayType.HOTEL_ROOM,
    location: "Copenhagen, Denmark",
    country: "Denmark",
    streetLine1: "Nyhavn 31",
    city: "Copenhagen",
    stateRegion: "Capital",
    postalCode: "1051",
    lat: 55.6797,
    lng: 12.5897,
    pricePerNight: 168,
    weekday: 158,
    weekend: 198,
    maxGuests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
  },
  {
    title: "Gamla Stan attic",
    description: "Original beams; quiet lane off Västerlånggatan.",
    stayType: StayType.RENTAL_ROOM,
    location: "Stockholm, Sweden",
    country: "Sweden",
    streetLine1: "Västerlånggatan 48",
    city: "Stockholm",
    stateRegion: "Stockholm County",
    postalCode: "111 29",
    lat: 59.3251,
    lng: 18.0719,
    pricePerNight: 152,
    weekday: 142,
    weekend: 182,
    maxGuests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
  },
  {
    title: "Aker Brygge waterfront",
    description: "Modern line; ferries to islands at the pier.",
    stayType: StayType.RENTAL_ROOM,
    location: "Oslo, Norway",
    country: "Norway",
    streetLine1: "Strandpromenaden 2",
    city: "Oslo",
    stateRegion: "Oslo",
    postalCode: "0252",
    lat: 59.9092,
    lng: 10.7226,
    pricePerNight: 162,
    weekday: 152,
    weekend: 192,
    maxGuests: 3,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1.5,
  },
  {
    title: "Sablon chocolate district flat",
    description: "EU quarter walk; weekend antiques market.",
    stayType: StayType.RENTAL_ROOM,
    location: "Brussels, Belgium",
    country: "Belgium",
    streetLine1: "Rue des Bouchers 24",
    city: "Brussels",
    stateRegion: "Brussels-Capital",
    postalCode: "1000",
    lat: 50.8467,
    lng: 4.3525,
    pricePerNight: 102,
    weekday: 96,
    weekend: 122,
    maxGuests: 3,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
  },
  {
    title: "Castle District guest room",
    description: "Stone staircase; ruin bars in walking distance.",
    stayType: StayType.BNB_ROOM,
    location: "Budapest, Hungary",
    country: "Hungary",
    streetLine1: "Fortuna u. 14",
    city: "Budapest",
    stateRegion: "Budapest",
    postalCode: "1014",
    lat: 47.5022,
    lng: 19.0345,
    pricePerNight: 64,
    weekday: 60,
    weekend: 78,
    maxGuests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
  },
  {
    title: "Śródmieście art-nouveau studio",
    description: "High ceilings near Old Town Square.",
    stayType: StayType.RENTAL_ROOM,
    location: "Warsaw, Poland",
    country: "Poland",
    streetLine1: "Marszałkowska 68",
    city: "Warsaw",
    stateRegion: "Masovian",
    postalCode: "00-545",
    lat: 52.2297,
    lng: 21.0122,
    pricePerNight: 72,
    weekday: 68,
    weekend: 88,
    maxGuests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
  },
  {
    title: "Maxvorstadt museum quarter studio",
    description: "Quiet side street between Pinakotheken.",
    stayType: StayType.HOTEL_ROOM,
    location: "Munich, Germany",
    country: "Germany",
    streetLine1: "Theresienstraße 72",
    city: "Munich",
    stateRegion: "Bavaria",
    postalCode: "80333",
    lat: 48.1475,
    lng: 11.5758,
    pricePerNight: 122,
    weekday: 114,
    weekend: 142,
    maxGuests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
  },
  {
    title: "Chartrons riverside stay",
    description: "Wine bars quay-side; Cité du Vin nearby.",
    stayType: StayType.RENTAL_ROOM,
    location: "Bordeaux, France",
    country: "France",
    streetLine1: "36 Quai des Chartrons",
    city: "Bordeaux",
    stateRegion: "Nouvelle-Aquitaine",
    postalCode: "33300",
    lat: 44.8624,
    lng: -0.568,
    pricePerNight: 108,
    weekday: 100,
    weekend: 128,
    maxGuests: 2,
    bedrooms: 1,
    beds: 2,
    bathrooms: 1,
  },
  {
    title: "Santa Cruz alley apartment",
    description: "Orange trees in the patio; cathedral bells at noon.",
    stayType: StayType.BNB_ROOM,
    location: "Seville, Spain",
    country: "Spain",
    streetLine1: "Callejon del Agua 6",
    city: "Seville",
    stateRegion: "Andalusia",
    postalCode: "41004",
    lat: 37.3891,
    lng: -5.9926,
    pricePerNight: 86,
    weekday: 80,
    weekend: 104,
    maxGuests: 3,
    bedrooms: 1,
    beds: 2,
    bathrooms: 1,
  },
  {
    title: "West End Victorian duplex room",
    description: "Kelvingrove Park ten minutes on foot.",
    stayType: StayType.BNB_ROOM,
    location: "Glasgow, UK",
    country: "United Kingdom",
    streetLine1: "12 Clifton St",
    city: "Glasgow",
    stateRegion: "Scotland",
    postalCode: "G3 7LD",
    lat: 55.8734,
    lng: -4.2891,
    pricePerNight: 82,
    weekday: 76,
    weekend: 98,
    maxGuests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
  },
  {
    title: "Bryggen timber loft",
    description: "Fjord views; Fløibanen funicular nearby.",
    stayType: StayType.RENTAL_ROOM,
    location: "Bergen, Norway",
    country: "Norway",
    streetLine1: "Strandgaten 209",
    city: "Bergen",
    stateRegion: "Vestland",
    postalCode: "5004",
    lat: 60.3943,
    lng: 5.3251,
    pricePerNight: 138,
    weekday: 128,
    weekend: 162,
    maxGuests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
  },
  {
    title: "Design District studio",
    description: "Sauna building; tram to harbor in minutes.",
    stayType: StayType.HOTEL_ROOM,
    location: "Helsinki, Finland",
    country: "Finland",
    streetLine1: "Erottajankatu 15",
    city: "Helsinki",
    stateRegion: "Uusimaa",
    postalCode: "00130",
    lat: 60.1666,
    lng: 24.9436,
    pricePerNight: 128,
    weekday: 118,
    weekend: 154,
    maxGuests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
  },
  {
    title: "Capitol Hill craftsman room",
    description: "Fir floors and breakfast nook; Link light rail nearby.",
    stayType: StayType.BNB_ROOM,
    location: "Seattle, WA",
    country: "United States",
    streetLine1: "1207 E Pike St",
    city: "Seattle",
    stateRegion: "WA",
    postalCode: "98122",
    lat: 47.6143,
    lng: -122.3147,
    pricePerNight: 118,
    weekday: 110,
    weekend: 142,
    maxGuests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
  },
  {
    title: "Back Bay brownstone garden unit",
    description: "Private entrance; green line to downtown.",
    stayType: StayType.RENTAL_ROOM,
    location: "Boston, MA",
    country: "United States",
    streetLine1: "337 Beacon St",
    city: "Boston",
    stateRegion: "MA",
    postalCode: "02116",
    lat: 42.3503,
    lng: -71.081,
    pricePerNight: 198,
    weekday: 188,
    weekend: 228,
    maxGuests: 3,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
  },
  {
    title: "LoDo loft with mountain glimpses",
    description: "Union Station blocks away; weekday remote-work desk.",
    stayType: StayType.RENTAL_ROOM,
    location: "Denver, CO",
    country: "United States",
    streetLine1: "1499 Blake St",
    city: "Denver",
    stateRegion: "CO",
    postalCode: "80202",
    lat: 39.7539,
    lng: -104.9991,
    pricePerNight: 132,
    weekday: 124,
    weekend: 158,
    maxGuests: 3,
    bedrooms: 1,
    beds: 2,
    bathrooms: 1,
  },
  {
    title: "Palermo Soho PH",
    description: "Balcony grill; plaza and bars at the corner.",
    stayType: StayType.RENTAL_ROOM,
    location: "Buenos Aires, Argentina",
    country: "Argentina",
    streetLine1: "Guatemala 4582",
    city: "Buenos Aires",
    stateRegion: "CABA",
    postalCode: "C1425",
    lat: -34.5889,
    lng: -58.4248,
    pricePerNight: 62,
    weekday: 58,
    weekend: 76,
    maxGuests: 3,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
  },
  {
    title: "Jardins high-rise suite",
    description: "Paulista Ave ten minutes; concierge desk.",
    stayType: StayType.HOTEL_ROOM,
    location: "São Paulo, Brazil",
    country: "Brazil",
    streetLine1: "Alameda Campinas 266",
    city: "São Paulo",
    stateRegion: "SP",
    postalCode: "01404-000",
    lat: -23.5614,
    lng: -46.6565,
    pricePerNight: 68,
    weekday: 62,
    weekend: 82,
    maxGuests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
  },
];
